language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10-dev

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install .

script:
  - cd tests/
  - pytest -v .

after_success:
  - coveralls
