# travis-ci.com is currently not used,
# and this file may be outdated.
#
# GitHub Actions are used:
# configured via the files in the directory:
# `.github/workflows/`
language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10-dev

addons:
  apt:
    update: true
    packages:
    - graphviz

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  # create sdist and install from it
  - python setup.py sdist
  - pip install dist/-*.tar.gz

script:
  - cd tests/
  - pytest -v .

after_success:
  - coveralls
